# This workflow is responsible for:
# - publishing artifacts to Maven Central
# - building and publishing javadocs to the git repository.
# It is triggered when a new release is created.

name: Publish Release
on:
  release:
    types: [created]
  workflow_dispatch:
    # Allow this workflow to be triggered manually

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build distribution
        run: |
          make setup publish_deps
          make build_dist

      - name: Publish distribution on pypi.org
        # We don't actually want to publish just yet.
        # uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   password: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "Listing distribution files in lieu of actual publishing at this time."
          ls -al dist
